name: Download-and-extract-v2

on:
  schedule:
    - cron: '0 2-4 * * 5'

jobs:
  build:
    name: Build
    env:
      USER_NAME: anothereideeznuts
      USER_EMAIL: another.eidos.cgs@gmail.com
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [22.x]
        python-version: [3.12]
    steps:
      - name: test
        run: echo aaaaaa
