name: Publish on Netlify

on:
  workflow_dispatch: ~

jobs:
  build:
    name: Build Asset Site on Netlify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - uses: actions/setup-node@v4.2.0
      with:
        node-version: '22'
        cache: 'npm'

    - name: Run netlify CLI
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN:  ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        npm install netlify
        npm run netlify -- deploy --dir=_site --alias ${{ github.ref_name }}